### ISSUE TITLE
plugin.yml ? 1.12.2 & latest build of the plugin

### ISSUE THREAD

**Issue by Lalamexx** [knokko/custom-items-gradle#177]
```
Could not load 'plugins\Editor.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
```

Someone ? 😫

**Comment by Lalamexx** [comment]
Fixed, don't take beta

**Comment by knokko** [comment]
More accurately, do **not** put **Editor.jar** in your plugins folder.
