### ISSUE TITLE
1.20.1 filling console with error messages

### ISSUE THREAD

**Issue by TheDemonicNinja** [knokko/custom-items-gradle#256]
Error Log
```
[16:40:45 WARN]: [CustomItems] Task #45 for CustomItems v12.3 generated an exception
java.lang.IllegalArgumentException: Illegal Capacity: -1
        at java.util.ArrayList.<init>(ArrayList.java:160) ~[?:?]
        at nl.knokko.customitems.plugin.tasks.updater.LoreUpdater.updateDurability(LoreUpdater.java:88) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.tasks.updater.ItemUpdater.upgradeLore(ItemUpdater.java:459) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.tasks.updater.ItemUpdater.upgradeCustomItem(ItemUpdater.java:415) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.tasks.updater.ItemUpdater.maybeUpdate(ItemUpdater.java:297) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.tasks.updater.ItemUpdater.updateEquipmentPiece(ItemUpdater.java:99) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.tasks.updater.ItemUpdater.updateEquipment(ItemUpdater.java:94) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.tasks.updater.ItemUpdater.lambda$start$0(ItemUpdater.java:56) ~[CustomItems.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-58]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-58]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by knokko** [comment]
This will be fixed in KCI 12.4
