### ISSUE TITLE
Repair Skript support

### ISSUE THREAD

**Issue by knokko** [knokko/custom-items-gradle#310]
The Skript support seems to be broken. I should fix it once I have more time.
```
[20:17:12 ERROR]: Error occurred while enabling CustomItems v12.11 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
        at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1223) ~[Skript-2.6.4_4.jar:?]
        at ch.njol.skript.Skript.registerAddon(Skript.java:1245) ~[Skript-2.6.4_4.jar:?]
        at nl.knokko.customitems.plugin.multisupport.skript.CISkriptAddon.enable(CISkriptAddon.java:13) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.multisupport.skript.SkriptSupport.onEnable(SkriptSupport.java:12) ~[CustomItems.jar:?]
        at nl.knokko.customitems.plugin.CustomItemsPlugin.onEnable(CustomItemsPlugin.java:118) ~[CustomItems.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:197) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.common.commands.CommandServerUtils.handleLoadPlugin(CommandServerUtils.java:198) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:189) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[ServerUtils-Bukkit-3.5.5-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:943) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2349) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by knokko** [comment]
This was not as bad as I originally expected: this error only happens when the plug-in is enabled via PlugMan. Anyway, it will be fixed in v13.
